#!/usr/bin/env bash
# Snap applications grouped by category.

SNAP_ESSENTIAL=(
  "spotify"             # Music streaming
)

SNAP_OPTIONAL=(
  "firefox"             # Web browser
  "thunderbird"         # Email client
)
