#!/usr/bin/env bash
# Flatpak applications grouped by category.
# Each array element is a Flatpak app ID.

FLATPAK_ESSENTIAL=(
  "org.videolan.VLC"                    # Media Player
)

FLATPAK_DEV=(
  "com.slack.Slack"                     # Slack
  "com.axosoft.GitKraken"               # Git GUI
  "md.obsidian.Obsidian"                # Notes
  "io.github.shiftey.Desktop"           # GitHub Desktop
)

FLATPAK_OPTIONAL=(
  "com.discordapp.Discord"              # Discord
  "com.obsproject.Studio"               # OBS Studio
  "org.gimp.GIMP"                       # Image editor
  "org.kde.kdenlive"                    # Video editor
  "net.nokyan.Resources"                # System monitor
  "org.gnome.Calendar"                  # Calendar
  "org.kde.labplot"                     # Data analysis
  "com.protonvpn.www"                   # ProtonVPN
  "me.proton.Mail"                      # ProtonMail
  "io.github.amit9838.mousam"           # Weather app
)
