#!/usr/bin/env bash
# Global Composer packages.
# Note: phpcs/phpcbf are installed by the phpcs module.

COMPOSER_GLOBAL_PACKAGES=(
  "phpstan/phpstan"                 # PHPStan static analysis
  "vimeo/psalm"                     # Psalm static analysis
  "friendsofphp/php-cs-fixer"      # PHP-CS-Fixer code formatter
)
