#!/usr/bin/env bash
# NVM version and global npm packages.

NVM_INSTALL_VERSION="v0.40.3"

NPM_GLOBAL_PACKAGES=(
  @openai/codex
  @google/gemini-cli
  yarn
  pnpm
  npm-check-updates
  eslint
  prettier
  serve
  vite
)
